---
env:
  browser: true
  es2021: true
  node: true
  es6: true
  jest: true

settings:
  react:
    version: 'detect'

extends:
  - eslint:recommended
  - airbnb-base
  - prettier
  - plugin:react/recommended
  - plugin:react-hooks/recommended

parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true

plugins:
  - prettier
  - react
  - react-hooks

rules:
  no-console: 0
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]
  consistent-return: [0, { 'treatUndefinedAsUnspecified': true }]
  react/jsx-uses-react: 0
  react/react-in-jsx-scope: 0
